### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ashishagarwal2023**
dunt ask, i just improved readme.,  I will re-edit this tommorow as im free

### CODE REVIEW

**Comment by I-No-oNe** [comment]
> You removed the contribution section and the module section, please return them.
(It's my personal thoughts)

**Comment by ashishagarwal2023** [comment]
Module section? Yo mean the , uh, modules list? It doesn't look good here tho

**Comment by ashishagarwal2023** [comment]
After merging this I'll add conmtributors (it will be a issue if I try rn)

**Comment by ashishagarwal2023** [comment]
@all-contributors add @ItziSpyder for coding, owner, docs, ideas, bugs

**Comment by ashishagarwal2023** [comment]
its not installed here ill tell itzispyder to do

**Comment by I-No-oNe** [comment]
> Module section? Yo mean the , uh, modules list? It doesn't look good here tho

So find a solution(if my opinion matters to you)

**Comment by ashishagarwal2023** [comment]
Just merge bruh @ItziSpyder

**Comment by I-No-oNe** [comment]
> Bro, let ItziSpyder to decide be **himself**.
> ***(And be aware that just because u are a dev ur PRs wont always be accepted)***

**Pull request closed without merging**
