### PR TITLE
Added `VersionRelativeHud`

### PR DESCRIPTION
**Pull request by I-No-oNe**
## Type of change

- [ ] Bug fix
- [x] New feature

## Description

> A hud to dispaly the cc version.

## Related issues

Mention any issues that this pull request relates to.

# Checklist:

- [x] My code follows the style guidelines of ItziSpyder(ImproperIssues).
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.
- [x] I have joined  the [ClickCrystals]((https://discord.com/invite/tMaShNzNtP)) Discord.

### CODE REVIEW

**Comment by I-No-oNe** [comment]
Please be aware this hud display the **ClickCrystals version** and not the mc version.

**Comment by ashishagarwal2023** [comment]
Bro who would use it ....

**Comment by ItziSpyder** [comment]
VersionRelativeHud, respectfully, would be absolutely useless in pvp/survival/uhc/etc. If users want to know what version of CC they are using, you already PR'ed `,version` + people can just open up the CC GUI

**Comment by I-No-oNe** [comment]
K, ty

**Pull request closed without merging**
