### PR TITLE
Add execute permission to gradlew (Linux)

### PR DESCRIPTION
**Pull request by Ceptea**
This adds the execute permission to gradlew.

### CODE REVIEW

**Comment by I-No-oNe** [comment]
what did u changed? 🤣

**Comment by Ceptea** [comment]
I added the execute permission to the linux gradlew script, to make it easier to execute it.

**Comment by I-No-oNe** [comment]
U added nothing 💀 (look on the files change)

**Comment by Ceptea** [comment]
I marked the file as executeable you just don't see it.

**Comment by I-No-oNe** [comment]
Oh(let's wait to @ItziSpyder to accept it, ig 🤷‍♂️)

**Pull request closed without merging**
